language: php
dist: xenial

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer install --prefer-dist --no-interaction

script: "vendor/bin/phpunit -c ./test/$TEST_DRIVER.phpunit.xml"

before_script:
  - cp test/properties.travis.inc.php test/properties.inc.php
  - if [ $TEST_DRIVER == 'mysql' ]; then mysql -u root -e "SET GLOBAL sql_mode = 'STRICT_TRANS_TABLES';"; fi;

jobs:
  include:
    - php: 5.6
      env: TEST_DRIVER=sqlite

    - php: 7.0
      env: TEST_DRIVER=sqlite

    - php: 7.1
      env: TEST_DRIVER=sqlite

    - php: 7.2
      env: TEST_DRIVER=sqlite

    - php: 7.3
      env: TEST_DRIVER=sqlite

    - php: 7.4
      env: TEST_DRIVER=sqlite

    - php: 5.6
      env: TEST_DRIVER=mysql
      services: mysql

    - php: 7.0
      env: TEST_DRIVER=mysql
      services: mysql

    - php: 7.1
      env: TEST_DRIVER=mysql
      services: mysql

    - php: 7.2
      env: TEST_DRIVER=mysql
      services: mysql

    - php: 7.3
      env: TEST_DRIVER=mysql
      services: mysql

    - php: 7.4
      env: TEST_DRIVER=mysql
      services: mysql

    - php: 5.6
      env: TEST_DRIVER=pgsql
      services: postgresql
      addons:
        postgresql: "9.6"

    - php: 7.0
      env: TEST_DRIVER=pgsql
      services: postgresql
      addons:
        postgresql: "9.6"

    - php: 7.1
      env: TEST_DRIVER=pgsql
      services: postgresql
      addons:
        postgresql: "9.6"

    - php: 7.2
      env: TEST_DRIVER=pgsql
      services: postgresql
      addons:
        postgresql: "9.6"

    - php: 7.3
      env: TEST_DRIVER=pgsql
      services: postgresql
      addons:
        postgresql: "9.6"

    - php: 7.4
      env: TEST_DRIVER=pgsql
      services: postgresql
      addons:
        postgresql: "9.6"
