language: php
script: "phpunit -c ./test/complete.phpunit.xml"
env:
  matrix:
    - TEST_DRIVER=mysql
    - TEST_DRIVER=sqlite

services: mysql

# Set php versions
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install --prefer-dist --no-interaction
  - cp test/properties.travis.inc.php test/properties.inc.php
  - mysql -e 'create database xpdotest;'

cache:
  directories:
    - vendor/
